# Generated by Django 5.0 on 2024-01-21 18:32

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MachineBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MachineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=20)),
                ('customerMessage', models.TextField()),
                ('customerGender', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.gender')),
            ],
        ),
        migrations.CreateModel(
            name='BrandImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandImage', models.ImageField(upload_to='brand/')),
                ('brandName', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.machinebrand')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uu_id', models.UUIDField(default=uuid.uuid4)),
                ('machineName', models.CharField(max_length=50)),
                ('machinePrice', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('machineDescription', models.CharField(max_length=50000)),
                ('machineNegotiatable', models.BooleanField(default=False)),
                ('machineImage', models.ImageField(upload_to='images/')),
                ('is_sale', models.BooleanField(default=False)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('user', models.CharField(default='admin', max_length=1000)),
                ('dt', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('machineBrand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.machinebrand')),
                ('machineCategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.machinecategory')),
            ],
        ),
    ]
